// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiUk8ZTMduw200cl5BdT4ycFxoCpxPz5k',
    appId: '1:254283327784:android:dbb7bac2eef9f706fb481d',
    messagingSenderId: '254283327784',
    projectId: 'taskmanager-15e71',
    storageBucket: 'taskmanager-15e71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEFy31EirxUIq05YipFon65vSN5y4iIpc',
    appId: '1:254283327784:ios:8cfc04f0391683e9fb481d',
    messagingSenderId: '254283327784',
    projectId: 'taskmanager-15e71',
    storageBucket: 'taskmanager-15e71.firebasestorage.app',
    iosClientId: '254283327784-dieu4it1cq37ve7ksho2rte90bd8kebh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterlearniti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUZGdfrmUbGDekFJ10-_m25NWHWrGz3-Q',
    appId: '1:254283327784:web:73a069174c5e84edfb481d',
    messagingSenderId: '254283327784',
    projectId: 'taskmanager-15e71',
    authDomain: 'taskmanager-15e71.firebaseapp.com',
    storageBucket: 'taskmanager-15e71.firebasestorage.app',
    measurementId: 'G-DJV8KH745Z',
  );
}
